framework:
    default_locale: fr
    enabled_locales: '%app.enabled_locales%'
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks: [en, fr]
        providers:
